apiVersion: v1
kind: Service
metadata:
  name: vote-back-{{.Release.Name}}
  labels:
    name: vote-back-{{.Release.Name}}
  namespace: ecptrue
spec:
  ports:
  - port: 6379
  selector:
    app: vote-back-{{.Release.Name}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNameFront }}
  labels:
    name: {{ .Values.serviceNameFront }}
  namespace: ecptrue
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: vote-front-{{.Release.Name}}
